# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby-mpi 0.3.2 ruby lib
# stub: ext/mpi/extconf.rb

Gem::Specification.new do |s|
  s.name = "ruby-mpi"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Seiya Nishizawa"]
  s.date = "2016-02-15"
  s.description = "A ruby binding of Message Passing Interface (MPI), which is an API specification that allows processes to communicate with one another by sending and receiving messages."
  s.email = "seiya@gfd-dennou.org"
  s.extensions = ["ext/mpi/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/mpi/extconf.rb",
    "ext/mpi/mpi.c",
    "lib/mpi.rb",
    "lib/mpi/utils.rb",
    "ruby-mpi.gemspec",
    "samples/hello.rb",
    "samples/narray.rb",
    "samples/narray_offset.rb",
    "spec/ruby-mpi_spec.rb",
    "spec/spec_helper.rb",
    "test/test_utils.rb"
  ]
  s.homepage = "http://github.com/seiya/ruby-mpi"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "A ruby binding of MPI"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<numru-narray>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
    else
      s.add_dependency(%q<numru-narray>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
    end
  else
    s.add_dependency(%q<numru-narray>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
  end
end

