# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby-mpi 0.4.0 ruby lib
# stub: ext/mpi/extconf.rb

Gem::Specification.new do |s|
  s.name = "ruby-mpi".freeze
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Seiya Nishizawa".freeze]
  s.date = "2024-11-22"
  s.description = "A ruby binding of Message Passing Interface (MPI), which is an API specification that allows processes to communicate with one another by sending and receiving messages.".freeze
  s.email = "seiya@gfd-dennou.org".freeze
  s.extensions = ["ext/mpi/extconf.rb".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/mpi/extconf.rb",
    "ext/mpi/mpi.c",
    "lib/mpi.rb",
    "lib/mpi/utils.rb",
    "ruby-mpi.gemspec",
    "samples/hello.rb",
    "samples/kmeans.rb",
    "samples/narray.rb",
    "samples/narray_offset.rb",
    "samples/pi.rb",
    "spec/ruby-mpi_spec.rb",
    "spec/spec_helper.rb",
    "test/test_utils.rb"
  ]
  s.homepage = "http://github.com/gfd-dennou-club/ruby-mpi".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.2.5".freeze
  s.summary = "A ruby binding of MPI".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<numru-narray>.freeze, ["~> 1.0"])
    s.add_development_dependency(%q<rspec>.freeze, [">= 2.3.0"])
    s.add_development_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_development_dependency(%q<jeweler>.freeze, [">= 1.5.2"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_development_dependency(%q<rake-compiler>.freeze, [">= 0"])
  else
    s.add_dependency(%q<numru-narray>.freeze, ["~> 1.0"])
    s.add_dependency(%q<rspec>.freeze, [">= 2.3.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 1.5.2"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<rake-compiler>.freeze, [">= 0"])
  end
end

